import React, { useEffect, useState } from "react";
import { Alert, Modal, Pressable, Text, TextInput, View } from "react-native";
import { localeMeta, t, type Locale } from "@/lib/i18n";
import { hasPin, savePin } from "@/lib/pin-security";
import MaterialIcons from "@expo/vector-icons/MaterialIcons";

export function FallbackPinCard({ locale }: { locale: Locale }) {
  const [configured, setConfigured] = useState(false); const [visible, setVisible] = useState(false); const [pin, setPin] = useState(""); const isRTL = localeMeta[locale].direction === "rtl";
  useEffect(() => { hasPin().then(setConfigured).catch(() => setConfigured(false)); }, []);
  const submit = async () => { try { await savePin(pin); setConfigured(true); setPin(""); setVisible(false); Alert.alert(t(locale, "fallbackPin"), t(locale, "pinSaved")); } catch { Alert.alert(t(locale, "fallbackPin"), t(locale, "pinInvalid")); } };
  return <><View style={{ borderTopWidth: 1, borderTopColor: "#F0EEF6", paddingTop: 13, flexDirection: isRTL ? "row-reverse" : "row", alignItems: "center", gap: 10 }}><MaterialIcons name="lock-outline" size={19} color="#7C5CFC" /><View style={{ flex: 1, alignItems: isRTL ? "flex-end" : "flex-start" }}><Text style={{ color: "#28243E", fontSize: 12, fontWeight: "800" }}>{t(locale, "fallbackPin")}</Text><Text style={{ color: "#9996A8", fontSize: 10 }}>{configured ? t(locale, "pinSaved") : t(locale, "setFallbackPin")}</Text></View><Pressable onPress={() => setVisible(true)} style={{ backgroundColor: "#F0ECFF", borderRadius: 10, paddingHorizontal: 10, paddingVertical: 8 }}><Text style={{ color: "#6C4EE4", fontSize: 10, fontWeight: "900" }}>{t(locale, "setFallbackPin")}</Text></Pressable></View><Modal visible={visible} transparent animationType="fade" onRequestClose={() => setVisible(false)}><View style={{ flex: 1, backgroundColor: "rgba(26,20,46,0.4)", justifyContent: "center", padding: 24 }}><View style={{ backgroundColor: "#FFFFFF", borderRadius: 24, padding: 20, gap: 14 }}><Text style={{ color: "#28243E", fontSize: 18, fontWeight: "900", textAlign: isRTL ? "right" : "left" }}>{t(locale, "fallbackPin")}</Text><TextInput value={pin} onChangeText={setPin} keyboardType="number-pad" secureTextEntry maxLength={6} placeholder={t(locale, "pinPlaceholder")} placeholderTextColor="#B1ADBC" style={{ backgroundColor: "#F8F7FC", borderRadius: 13, paddingHorizontal: 14, paddingVertical: 13, color: "#28243E", textAlign: "center", letterSpacing: 4 }} /><Pressable onPress={submit} style={{ backgroundColor: "#7C5CFC", borderRadius: 14, paddingVertical: 13, alignItems: "center" }}><Text style={{ color: "#FFFFFF", fontWeight: "900" }}>{t(locale, "save")}</Text></Pressable><Pressable onPress={() => setVisible(false)}><Text style={{ color: "#9996A8", textAlign: "center", fontWeight: "800" }}>{t(locale, "cancel")}</Text></Pressable></View></View></Modal></>;
}
