# تنظیمات حافظه و بهینه‌سازی جاوا برای بیلد اندروید (افزایش Heap و Metaspace برای جلوگیری از خطای کمبود حافظه)
org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m -XX:+HeapDumpOnOutOfMemoryError

# استفاده از کتابخانه‌های اندروید ایکس (AndroidX)
android.useAndroidX=true

# فعال‌سازی قابلیت Jetifier برای تبدیل خودکار کتابخانه‌های قدیمی به AndroidX
android.enableJetifier=true
