import React, { useEffect, useState } from "react";
import { Alert, Platform, Pressable, ScrollView, Switch, Text, TextInput, View } from "react-native";
import * as LocalAuthentication from "expo-local-authentication";
import { ScreenContainer } from "@/components/screen-container";
import { AppIcon } from "@/components/finance-components";
import { localeMeta, type Locale, t } from "@/lib/i18n";
import { useFinance } from "@/lib/finance-store";
import { defaultReminderSettings, getReminderSettings, saveReminderSettings, type ReminderSettings } from "@/lib/reminder-service";
import { FallbackPinCard } from "@/components/fallback-pin-card";
import { NotificationHistoryCard } from "@/components/notification-history-card";
import { resetFeatureTour } from "@/components/feature-tour-modal";

const languages: Locale[] = ["fa", "en", "ar", "tr"];

export default function SettingsScreen() {
  const { locale, setLocale, pieUnlocked, biometricEnabled, setBiometricEnabled } = useFinance();
  const [reminders, setReminders] = useState<ReminderSettings>(defaultReminderSettings);
  const isRTL = localeMeta[locale].direction === "rtl";
  useEffect(() => { getReminderSettings().then(setReminders); }, []);

  const updateReminder = async (patch: Partial<ReminderSettings>) => {
    const next = { ...reminders, ...patch };
    setReminders(next);
    try { const saved = await saveReminderSettings(next, locale); setReminders(saved); } catch { Alert.alert(t(locale, "reminders"), t(locale, "notificationsUnavailable")); }
  };
  const enableBiometric = async (value: boolean) => {
    if (!value) { setBiometricEnabled(false); return; }
    if (Platform.OS === "web") { Alert.alert(t(locale, "biometricLock"), t(locale, "biometricUnavailable")); return; }
    const hasHardware = await LocalAuthentication.hasHardwareAsync();
    const isEnrolled = await LocalAuthentication.isEnrolledAsync();
    if (!hasHardware || !isEnrolled) { Alert.alert(t(locale, "biometricLock"), t(locale, "biometricUnavailable")); return; }
    setBiometricEnabled(true);
  };
  const dayValue = (value: string) => Math.min(28, Math.max(1, Number(value.replace(/[^0-9]/g, "")) || 1));

  return <ScreenContainer containerClassName="bg-[#F8F7FC]" safeAreaClassName="bg-[#F8F7FC]"><ScrollView contentContainerStyle={{ paddingHorizontal: 20, paddingTop: 14, paddingBottom: 30 }} showsVerticalScrollIndicator={false}>
    <View style={{ gap: 5, alignItems: isRTL ? "flex-end" : "flex-start" }}><Text style={{ color: "#9996A8", fontSize: 12, fontWeight: "600" }}>{t(locale, "appName")}</Text><Text style={{ color: "#28243E", fontSize: 28, fontWeight: "900" }}>{t(locale, "settings")}</Text></View>
    <View style={{ backgroundColor: "#FFFFFF", borderRadius: 24, padding: 18, marginTop: 22, borderWidth: 1, borderColor: "#EFEDF6", gap: 15 }}><View style={{ flexDirection: isRTL ? "row-reverse" : "row", alignItems: "center", gap: 11 }}><View style={{ width: 40, height: 40, borderRadius: 14, backgroundColor: "#F0ECFF", alignItems: "center", justifyContent: "center" }}><AppIcon name="translate" color="#7C5CFC" size={20} /></View><View style={{ gap: 3, alignItems: isRTL ? "flex-end" : "flex-start" }}><Text style={{ color: "#28243E", fontSize: 14, fontWeight: "900" }}>{t(locale, "language")}</Text><Text style={{ color: "#9996A8", fontSize: 11 }}>{localeMeta[locale].nativeLabel}</Text></View></View><View style={{ flexDirection: isRTL ? "row-reverse" : "row", gap: 8 }}>{languages.map((item) => <Pressable key={item} onPress={() => setLocale(item)} style={[{ flex: 1, borderRadius: 13, paddingVertical: 11, alignItems: "center", borderWidth: 1 }, locale === item ? { borderColor: "#7C5CFC", backgroundColor: "#F3F0FF" } : { borderColor: "#EEEAF5" }]}><Text style={{ color: locale === item ? "#6C4EE4" : "#9996A8", fontSize: 12, fontWeight: "900" }}>{localeMeta[item].nativeLabel}</Text></Pressable>)}</View></View>
    <View style={{ backgroundColor: "#FFFFFF", borderRadius: 24, padding: 18, marginTop: 16, borderWidth: 1, borderColor: "#EFEDF6", gap: 15 }}><View style={{ flexDirection: isRTL ? "row-reverse" : "row", alignItems: "center", gap: 11 }}><View style={{ width: 40, height: 40, borderRadius: 14, backgroundColor: "#FFF4DE", alignItems: "center", justifyContent: "center" }}><AppIcon name="notifications-none" color="#D49320" size={20} /></View><View style={{ flex: 1, gap: 3, alignItems: isRTL ? "flex-end" : "flex-start" }}><Text style={{ color: "#28243E", fontSize: 14, fontWeight: "900" }}>{t(locale, "reminders")}</Text><Text style={{ color: "#9996A8", fontSize: 11, textAlign: isRTL ? "right" : "left" }}>{Platform.OS === "web" ? t(locale, "notificationsUnavailable") : t(locale, "billReminderBody")}</Text></View></View><ReminderRow label={t(locale, "billReminder")} enabled={reminders.billEnabled} day={reminders.billDay} locale={locale} onToggle={(value) => updateReminder({ billEnabled: value })} onDay={(value) => updateReminder({ billDay: dayValue(value) })} /><ReminderRow label={t(locale, "budgetReminder")} enabled={reminders.budgetEnabled} day={reminders.budgetDay} locale={locale} onToggle={(value) => updateReminder({ budgetEnabled: value })} onDay={(value) => updateReminder({ budgetDay: dayValue(value) })} /></View>
    <View style={{ backgroundColor: "#FFFFFF", borderRadius: 24, padding: 18, marginTop: 16, borderWidth: 1, borderColor: "#EFEDF6", gap: 12 }}><View style={{ flexDirection: isRTL ? "row-reverse" : "row", alignItems: "center", gap: 11 }}><View style={{ width: 40, height: 40, borderRadius: 14, backgroundColor: "#EDE8FF", alignItems: "center", justifyContent: "center" }}><AppIcon name="fingerprint" color="#7C5CFC" size={21} /></View><View style={{ flex: 1, gap: 3, alignItems: isRTL ? "flex-end" : "flex-start" }}><Text style={{ color: "#28243E", fontSize: 14, fontWeight: "900" }}>{t(locale, "biometricLock")}</Text><Text style={{ color: "#9996A8", fontSize: 11, textAlign: isRTL ? "right" : "left" }}>{biometricEnabled ? t(locale, "biometricLockOn") : t(locale, "biometricLockOff")}</Text></View><Switch value={biometricEnabled} onValueChange={enableBiometric} trackColor={{ false: "#E5E1EF", true: "#B8A8FF" }} thumbColor={biometricEnabled ? "#7C5CFC" : "#FFFFFF"} /></View></View>
    <NotificationHistoryCard locale={locale} />
    <FallbackPinCard locale={locale} />
    <Pressable onPress={() => void resetFeatureTour()} style={({ pressed }) => [{ backgroundColor: "#F0ECFF", borderRadius: 18, padding: 16, flexDirection: isRTL ? "row-reverse" : "row", alignItems: "center", gap: 10 }, pressed && { opacity: 0.8 }]}><AppIcon name="school" color="#7C5CFC" size={20} /><Text style={{ color: "#6C4EE4", fontSize: 13, fontWeight: "900", flex: 1, textAlign: isRTL ? "right" : "left" }}>{t(locale, "replayTour")}</Text><AppIcon name="chevron-right" color="#7C5CFC" size={18} /></Pressable>
    <View style={{ backgroundColor: "#292044", borderRadius: 24, padding: 19, marginTop: 16, gap: 16 }}><View style={{ flexDirection: isRTL ? "row-reverse" : "row", alignItems: "center", gap: 11 }}><View style={{ width: 42, height: 42, borderRadius: 14, backgroundColor: "#47366E", alignItems: "center", justifyContent: "center" }}><AppIcon name="shopping-cart" color="#B8A8FF" size={20} /></View><View style={{ flex: 1, gap: 4, alignItems: isRTL ? "flex-end" : "flex-start" }}><Text style={{ color: "#FFFFFF", fontSize: 14, fontWeight: "900" }}>{t(locale, "bazaarReady")}</Text><Text style={{ color: "#BEB6DC", fontSize: 11, lineHeight: 17, textAlign: isRTL ? "right" : "left" }}>{t(locale, "bazaarNote")}</Text></View><View style={{ width: 9, height: 9, borderRadius: 5, backgroundColor: pieUnlocked ? "#68D9B6" : "#F5B544" }} /></View><View style={{ borderTopWidth: 1, borderTopColor: "#453765", paddingTop: 13, flexDirection: isRTL ? "row-reverse" : "row", justifyContent: "space-between" }}><Text style={{ color: "#BEB6DC", fontSize: 11 }}>{t(locale, "pieChartLocked")}</Text><Text style={{ color: pieUnlocked ? "#68D9B6" : "#F5B544", fontSize: 11, fontWeight: "900" }}>{pieUnlocked ? t(locale, "premiumUnlocked") : t(locale, "oneTimePurchase")}</Text></View></View>
    <View style={{ backgroundColor: "#FFFFFF", borderRadius: 24, padding: 18, marginTop: 16, borderWidth: 1, borderColor: "#EFEDF6", flexDirection: isRTL ? "row-reverse" : "row", alignItems: "center", gap: 11 }}><View style={{ width: 40, height: 40, borderRadius: 14, backgroundColor: "#EEF9F5", alignItems: "center", justifyContent: "center" }}><AppIcon name="phone-android" color="#2EBD85" size={20} /></View><View style={{ flex: 1, gap: 4, alignItems: isRTL ? "flex-end" : "flex-start" }}><Text style={{ color: "#28243E", fontSize: 13, fontWeight: "900" }}>{t(locale, "localData")}</Text><Text style={{ color: "#9996A8", fontSize: 11 }}>Pocket Budget · v1.0</Text></View></View>
  </ScrollView></ScreenContainer>;
}

function ReminderRow({ label, enabled, day, locale, onToggle, onDay }: { label: string; enabled: boolean; day: number; locale: Locale; onToggle: (value: boolean) => void; onDay: (value: string) => void }) { const isRTL = localeMeta[locale].direction === "rtl"; return <View style={{ flexDirection: isRTL ? "row-reverse" : "row", alignItems: "center", gap: 10, borderTopWidth: 1, borderTopColor: "#F0EEF6", paddingTop: 12 }}><View style={{ flex: 1, gap: 4, alignItems: isRTL ? "flex-end" : "flex-start" }}><Text style={{ color: "#28243E", fontSize: 12, fontWeight: "800" }}>{label}</Text><View style={{ flexDirection: isRTL ? "row-reverse" : "row", alignItems: "center", gap: 6 }}><Text style={{ color: "#9996A8", fontSize: 10 }}>{t(locale, "reminderDay")}</Text><TextInput value={String(day)} onChangeText={onDay} keyboardType="number-pad" maxLength={2} style={{ minWidth: 38, borderWidth: 1, borderColor: "#E7E3F2", borderRadius: 8, paddingVertical: 5, paddingHorizontal: 8, color: "#28243E", textAlign: "center", fontSize: 11 }} /></View></View><Switch value={enabled} onValueChange={onToggle} trackColor={{ false: "#E5E1EF", true: "#B8A8FF" }} thumbColor={enabled ? "#7C5CFC" : "#FFFFFF"} /></View>; }
